language: node_js
node_js:
- "stable"
cache: 
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: XP1LmC6Ib8zA4iFvHDaOzBI6+qs/COc+Z+1UapreJfhJcTDYmx6rgWavTggTczS8mX39fOEDfCXluwVHPOtDuhlXfYiYyqLyylkg8k9oRMvQQSb4ew4zGUTHRjhSbJh0uVH5r5CCEZW0k06b4mZP9oAS5XE/wPySEvxtx6DDSUci+yZI6FXnHh2V0QdZNKDmFLBlETBMQ5jjf/CJYb3ibvXUm2A/lm0jqhXWapcg4658MXgj1DQauGEtCSE3JGj1VIYk8dn+U1qYhufC7hPqGlhlkzHgSvf66ETL9anIRYe2fwWxscGhY3fZzwQuiiuHFjUlGyGTKLDYoTThjezPmtH2z3RDZIabsORhJmEQ02S166YieSjOdqceHtM0iBAVWWQpyK7DGFz+cICFoUEMWvah6hSTI4f1UHXL7Eg/Himw77saJlawHfXysR00Z9o/UiUUIeBluvaPBFfRrYaCdFae3AU0kmVRRunPoFvZ+xIlAa2qRMwqtisTi77kHTpQP1QCQZQMCQ0oBSPutLAk6ez0QY+3iZKMStgwAt4TJQBnyVhhcDwvmtJr+wk6v3QHkgpOM+QemWlkeaXL4OlnkEG4n0IGCxlQxjUAHjo6xxQL4ZSxR3yjd8zO1R6xqESiKp/y/9s8lBDCyKKBVpN78K3eyPotHqfCAunlGbkbOyc=
  app: wrong-calc-web
  on:
    repo: Scumworth/wrong-calc-web
